<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>bksh2ray</AssemblyName>
    <RootNamespace>bksh2ray</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.2.4</Version>
    <FileVersion>1.2.4</FileVersion>
    <AssemblyVersion>1.2.4</AssemblyVersion>
    <NoWarn>MSB3277</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="app.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>